### ISSUE TITLE
epg doesn't mach any channel of a m3u playlist

### ISSUE THREAD

**Issue by Shasoosh** [sebdelsol/sfvip-all#12]
Hey, 

Thanks for the app. I've downloaded the latest version and added an external epg (a gz url contains an xml)
My iptv is a .m3u8 url.

EPG seems to load (getting a green Ready) but I don't see a EPG button on the UI. Also clicking E on the keyboard doesn't do anything.

What am I missing?

**Comment by sebdelsol** [comment]
Could you please share your epg url and [your logs](https://github.com/sebdelsol/sfvip-all/issues/7#issuecomment-1892153440)

**Comment by Shasoosh** [comment]
Thanks for the reply.

Here are all my logs in one paste: https://pastebin.com/HX0TYSvi

My EPG: https://play-berry.net/xmltv.xml.gz

**Comment by sebdelsol** [comment]
The epg is correctly loaded indeed.
So there's an issue with matching the m3u channels with the epg channels.
To check why I would need the content of the .m3u8 response (I'm interested in `tvg-id` and `tvg-name` attributes).

**Comment by Shasoosh** [comment]
By content of the .m3u8 response you mean the content of the m3u8?
I've updated https://pastebin.com/HX0TYSvi with a list of all the `tvg-id` found inside the m3u8. There were no `tvg-name` there, though. I can share the actual url in private if it will be quicker to debug.

**Comment by sebdelsol** [comment]
It would be great to have the full content of some random channels found in the m3u

**Comment by sebdelsol** [comment]
BTW Have you tried to watch a channel (eg. channel24 which seems to be both in the m3u and the epg), and checked that you actually have the epg current schedule showing ? 
(the `e` key should toggle the full day schedule for the watched channel).

**Comment by Shasoosh** [comment]
`e` doesn't do anything on channel24. Looks like sharing the link is against their terms of service but you can register at raspberrytv dot net for a 72 free trial and select the Israel package. (no cc required)

**Comment by sebdelsol** [comment]
Sure I understand, I'll dot that.

**Comment by sebdelsol** [comment]
It should be fixed in v**1.4.12.27**

**Comment by Shasoosh** [comment]
Thanks. I’ve downloaded the new version. ‘e’ works but I can’t click on shows from the epg for the catchup feature (is that suppose to work? I have a 7 days back archive that I usually use on my Android device)

also I still can’t see the epg button on the right upper corner.

**Comment by sebdelsol** [comment]
> I can’t click on shows from the epg for the catchup feature (is that suppose to work? I have a 7 days back archive that I usually use on my Android device)

I might add it in a future version

>also I still can’t see the epg button on the right upper corner.

Note sure what you mean.

**Comment by Shasoosh** [comment]
I’ve e seen images with an epg button on the top right corner. I was under the impression that it opens a complete epg (not just for a specific channel)

![image](https://github.com/sebdelsol/sfvip-all/assets/2679978/f3edc8f5-8ef3-4019-a8c5-22c4a2f0ca96)

**Comment by sebdelsol** [comment]
oh I was not aware of this button...
Anyway _Sfvip All_ is a launcher of _Sfvip Player_ which is not open source. 
So I had to tinker a lot to make those new features work: I already have some hooks in _Sfvip Player_, but a button detection would prolly be a PITA to maintain...

**Comment by Shasoosh** [comment]
Yea I understand. I would love to see a full epg at some point with the ability to watch content a week back.

Thanks for the help!
